[package]
name = "genvandermonde"
version = "0.1.0"
edition = "2021"

[dependencies]
consensus = {package = "consensus", path="../../consensus"}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"